### ISSUE TITLE
Command Line usage crashing on example from README.md

### ISSUE THREAD

**Issue by alecjacobson** [pressureless/linear_algebra#19]
I copied the example from the readme into the [attached test.txt](https://github.com/pressureless/linear_algebra/files/5381578/test.txt) and tried to run my installation in command line mode using:

    python linear_algebra.py -o latex test.txt

but it appears to crash

```
Creating parser...
------------ 9.79 seconds ------------
Traceback (most recent call last):
  File "linear_algebra.py", line 32, in <module>
    for input in args.input: compile_la_file(input, parser_type)
  File "/Users/ajx/Repos/iheartla/la_parser/parser.py", line 289, in compile_la_file
    type_walker, start_node = parse_ir_node(content, model)
  File "/Users/ajx/Repos/iheartla/la_parser/parser.py", line 213, in parse_ir_node
    start_node = type_walker.walk(model)
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/walkers.py", line 18, in walk
    return walker(node, *args, **kwargs)
  File "/Users/ajx/Repos/iheartla/la_parser/type_walker.py", line 237, in walk_Start
    type_info = self.walk(stat_list[index], **kwargs)
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/walkers.py", line 18, in walk
    return walker(node, *args, **kwargs)
  File "/Users/ajx/Repos/iheartla/la_parser/type_walker.py", line 495, in walk_Expression
    value_info = self.walk(node.value, **kwargs)
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/walkers.py", line 18, in walk
    return walker(node, *args, **kwargs)
  File "/Users/ajx/Repos/iheartla/la_parser/type_walker.py", line 1155, in walk_Factor
    node_info = self.walk(node.op, **kwargs)
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/walkers.py", line 18, in walk
    return walker(node, *args, **kwargs)
  File "/Users/ajx/Repos/iheartla/la_parser/type_walker.py", line 679, in walk_Summation
    ret_info = self.walk(node.exp, **kwargs)
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/tatsu/walkers.py", line 18, in walk
    return walker(node, *args, **kwargs)
  File "/Users/ajx/Repos/iheartla/la_parser/type_walker.py", line 552, in walk_Multiply
    return self.make_mul_info(left_info, right_info)
  File "/Users/ajx/Repos/iheartla/la_parser/type_walker.py", line 557, in make_mul_info
    ret_type = self.type_inference(TypeInferenceEnum.INF_MUL, left_info.ir, right_info.ir)
  File "/Users/ajx/Repos/iheartla/la_parser/type_walker.py", line 1705, in type_inference
    left_line = left_info.parse_info.buffer.line_info(left_info.parse_info.pos)
AttributeError: 'ParseInfo' object has no attribute 'buffer'
``` 

Am I calling this correctly?

**Comment by pressureless** [comment]
The way you call that is correct.
I can generate the output using your command and input. I use Python3.7 and Tatsu 4.4.0
What's the version of Tatsu on your computer? Is it version 5.5.0?

**Comment by pressureless** [comment]
Please update the code, it should work now.

**Comment by pressureless** [comment]
I'm not sure whether it's related to TatSu module. It ran correctly on my local system(Python3.7+Tatsu4.4 and Python3.8 +Tatsu5.5).  Can you try this demo? [tatsu_test.py.txt](https://github.com/pressureless/linear_algebra/files/5386817/tatsu_test.py.txt)

It's a very simple demo with TatSu. If ```python tatsu_test.py.txt``` can generate output like this, then TatSu module should be fine.
<img width="687" alt="image" src="https://user-images.githubusercontent.com/8511053/96168028-2cb50c00-0eee-11eb-8a41-9e9ca3216143.png">

**Comment by alecjacobson** [comment]
Here's what I get:

Python version

3.7.9 (default, Aug 31 2020, 07:22:35)

[Clang 10.0.0 ]

Version info.

sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)

version: 4.4.0

compile ['3', '+', ['5', '*', ['(', ['10', '-', '20'], ')']]]

>

**Comment by pressureless** [comment]
It's very strange. Python3.7.9 still works for me.
<img width="873" alt="image" src="https://user-images.githubusercontent.com/8511053/96196626-d8298500-0f1d-11eb-9b00-8068af8d481d.png">

Based on the output, the parser is created successfully. I don't know why it fails to parse since the input is already very simple.
```
∑_i a_i b_i
where
a_i: ℝ
b_i: ℝ
```
The simplest input would be ```a=2```, the program may fail to parse this either.

**Comment by pressureless** [comment]
I encountered a similar [problem](https://github.com/iodide-project/pyodide/issues/740) before. 
But in that case, TatSu module is completely not working.

**Comment by yig** [comment]
Fixed with newer release versions.
