### ISSUE TITLE
Release .app doesn't appear to "Run"

### ISSUE THREAD

**Issue by alecjacobson** [pressureless/linear_algebra#20]
![image](https://user-images.githubusercontent.com/2241689/96155107-8c56eb80-0edd-11eb-842b-7daddcc29234.png)
Should I click "Run Program" to generate the C++/Latex code in the GUI?

When I do that I get a 

    Exception: 'NoneType' object has no attribute 'parse'

error.

**Comment by alecjacobson** [comment]
Running on the command line fails, too:

    /Users/ajx/Downloads/linear_algebra.app/Contents/MacOS/linear_algebra -o latex test.txt

same error as if I use it from git

```
Creating parser...
------------ 11.71 seconds ------------
Traceback (most recent call last):
  File "tatsu/contexts.py", line 218, in parse
  File "tatsu/grammars.py", line 782, in parse
  File "tatsu/grammars.py", line 790, in _parse_rhs
  File "tatsu/contexts.py", line 519, in _call
  File "tatsu/contexts.py", line 548, in _recursive_call
  File "tatsu/contexts.py", line 595, in _invoke_rule
  File "tatsu/grammars.py", line 390, in parse
  File "tatsu/grammars.py", line 390, in <listcomp>
  File "tatsu/grammars.py", line 517, in parse
  File "tatsu/contexts.py", line 802, in _positive_closure
  File "tatsu/grammars.py", line 517, in <lambda>
  File "tatsu/grammars.py", line 390, in parse
  File "tatsu/grammars.py", line 390, in <listcomp>
  File "tatsu/grammars.py", line 682, in parse
  File "tatsu/grammars.py", line 733, in parse
  File "tatsu/grammars.py", line 782, in parse
  File "tatsu/grammars.py", line 790, in _parse_rhs
  File "tatsu/contexts.py", line 519, in _call
  File "tatsu/contexts.py", line 548, in _recursive_call
  File "tatsu/contexts.py", line 595, in _invoke_rule
  File "tatsu/grammars.py", line 451, in parse
  File "tatsu/contexts.py", line 453, in _error
tatsu.exceptions.FailedParse: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "linear_algebra.py", line 32, in <module>
    elif args.input:
  File "la_parser/parser.py", line 291, in compile_la_file
    model = parser.parse(content, parseinfo=True)
  File "tatsu/grammars.py", line 1029, in parse
  File "tatsu/contexts.py", line 226, in parse
  File "tatsu/contexts.py", line 694, in _option
  File "tatsu/contexts.py", line 778, in _repeat
  File "tatsu/contexts.py", line 757, in _isolate
  File "tatsu/grammars.py", line 495, in <lambda>
  File "tatsu/grammars.py", line 733, in parse
  File "tatsu/grammars.py", line 782, in parse
  File "tatsu/grammars.py", line 790, in _parse_rhs
  File "tatsu/contexts.py", line 519, in _call
  File "tatsu/contexts.py", line 548, in _recursive_call
  File "tatsu/contexts.py", line 586, in _invoke_rule
  File "tatsu/contexts.py", line 694, in _option
  File "tatsu/contexts.py", line 717, in _optional
  File "tatsu/contexts.py", line 789, in _closure
  File "tatsu/grammars.py", line 495, in <lambda>
  File "tatsu/grammars.py", line 733, in parse
  File "tatsu/grammars.py", line 782, in parse
  File "tatsu/grammars.py", line 790, in _parse_rhs
  File "tatsu/contexts.py", line 519, in _call
  File "tatsu/contexts.py", line 548, in _recursive_call
  File "tatsu/contexts.py", line 586, in _invoke_rule
  File "tatsu/contexts.py", line 694, in _option
  File "tatsu/contexts.py", line 778, in _repeat
  File "tatsu/contexts.py", line 757, in _isolate
  File "tatsu/grammars.py", line 495, in <lambda>
  File "tatsu/grammars.py", line 733, in parse
  File "tatsu/grammars.py", line 782, in parse
  File "tatsu/grammars.py", line 790, in _parse_rhs
  File "tatsu/contexts.py", line 519, in _call
  File "tatsu/contexts.py", line 548, in _recursive_call
  File "tatsu/contexts.py", line 586, in _invoke_rule
  File "tatsu/contexts.py", line 694, in _option
  File "tatsu/contexts.py", line 717, in _optional
  File "tatsu/contexts.py", line 789, in _closure
  File "tatsu/grammars.py", line 495, in <lambda>
  File "tatsu/grammars.py", line 733, in parse
  File "tatsu/grammars.py", line 782, in parse
  File "tatsu/grammars.py", line 790, in _parse_rhs
  File "tatsu/contexts.py", line 519, in _call
  File "tatsu/contexts.py", line 548, in _recursive_call
  File "tatsu/contexts.py", line 586, in _invoke_rule
  File "tatsu/contexts.py", line 694, in _option
  File "tatsu/contexts.py", line 778, in _repeat
  File "tatsu/contexts.py", line 757, in _isolate
  File "tatsu/grammars.py", line 495, in <lambda>
  File "tatsu/grammars.py", line 733, in parse
  File "tatsu/grammars.py", line 782, in parse
  File "tatsu/grammars.py", line 790, in _parse_rhs
  File "tatsu/contexts.py", line 519, in _call
  File "tatsu/contexts.py", line 548, in _recursive_call
  File "tatsu/contexts.py", line 586, in _invoke_rule
  File "tatsu/contexts.py", line 694, in _option
  File "tatsu/contexts.py", line 717, in _optional
  File "tatsu/contexts.py", line 789, in _closure
  File "tatsu/grammars.py", line 495, in <lambda>
  File "tatsu/grammars.py", line 733, in parse
  File "tatsu/grammars.py", line 782, in parse
  File "tatsu/grammars.py", line 790, in _parse_rhs
  File "tatsu/contexts.py", line 519, in _call
  File "tatsu/contexts.py", line 548, in _recursive_call
  File "tatsu/contexts.py", line 595, in _invoke_rule
  File "tatsu/grammars.py", line 451, in parse
  File "tatsu/contexts.py", line 453, in _error
tatsu.exceptions.FailedParse: <exception str() failed>
[42178] Failed to execute script linear_algebra
```

**Comment by yig** [comment]
I messed up the packaging. I wasn't copying the grammar definition files. I'm working on it.

**Comment by pressureless** [comment]
The new release is [here](https://github.com/pressureless/linear_algebra/releases/tag/2020-10-15c-pyinstaller_macos).
