### ISSUE TITLE
This least squares example doesn't compile

### ISSUE THREAD

**Issue by yig** [pressureless/linear_algebra#21]
The following code:

```
given
p_i: ℝ^3: points on lines
d_i: ℝ^3: unit directions along lines

k_i = (p_i - (p_i⋅d_i)d_i)
a_i = <1,0,0> - d_i,1 d_i
b_i = <0,1,0> - d_i,2 d_i
c_i = <0,0,1> - d_i,3 d_i

M = [ ∑_i( a_i,1 - d_i,1 (d_i⋅a_i) )    ∑_i( a_i,2 - d_i,2 (d_i⋅a_i) )    ∑_i( a_i,3 - d_i,3 (d_i⋅a_i) )
      ∑_i( b_i,1 - d_i,1 (d_i⋅b_i) )    ∑_i( b_i,2 - d_i,2 (d_i⋅b_i) )    ∑_i( b_i,3 - d_i,3 (d_i⋅b_i) )
      ∑_i( c_i,1 - d_i,1 (d_i⋅c_i) )    ∑_i( c_i,2 - d_i,2 (d_i⋅c_i) )    ∑_i( c_i,3 - d_i,3 (d_i⋅c_i) ) ]

r = [ ∑_i( k_i⋅a_i )
      ∑_i( k_i⋅b_i )
      ∑_i( k_i⋅c_i ) ]

q = M^(-1) r
```

generates the following error:

```
Error on line 6 at column 1. Element hasn't been defined.
k_i = (p_i - (p_i⋅d_i)d_i)
^
```

**Comment by pressureless** [comment]
I need to adjust the code as follows.
```
given
p_i: ℝ^3: points on lines
d_i: ℝ^3: unit directions along lines

k_i = (p_i - (p_i⋅d_i)d_i)
a_i = [1,0,0]^T - d_i,0 d_i
b_i = [0,1,0]^T - d_i,1 d_i
c_i = [0,0,1]^T - d_i,2 d_i

M = [ (∑_i( a_i,0 - d_i,0 (d_i⋅a_i) ))    (∑_i( a_i,1 - d_i,1 (d_i⋅a_i) ))    (∑_i( a_i,2 - d_i,2 (d_i⋅a_i) ))
      (∑_i( b_i,0 - d_i,0 (d_i⋅b_i) ))    (∑_i( b_i,1 - d_i,1 (d_i⋅b_i) ))    (∑_i( b_i,2 - d_i,2 (d_i⋅b_i) ))
      (∑_i( c_i,0 - d_i,0 (d_i⋅c_i) ))    (∑_i( c_i,1 - d_i,1 (d_i⋅c_i) ))    (∑_i( c_i,2 - d_i,2 (d_i⋅c_i) )) ]

r = [ ∑_i( k_i⋅a_i )
      ∑_i( k_i⋅b_i )
      ∑_i( k_i⋅c_i ) ]

q = M^(-1) r
```
1. ```<``` and ```>``` is used in inner product now, we need bracket here. The current implementation is the same as Eigen, so we also need transpose here.
2. The current way is 0 indexing, so 3 is not suitable.
3. Summation has high precedence than square bracket now, so ```∑_i( a_i,0 - d_i,0 (d_i⋅a_i) )    ∑_i( a_i,1 - d_i,1 (d_i⋅a_i) )``` is considered as a single expression, we need parenthesis here.

**Comment by yig** [comment]
I tried your version with the latest code and I get:
```
Error on line 10 at column 11. Failed to parse sum: no available options
M = [ (∑_i( a_i,0 - d_i,0 (d_i⋅a_i) ))    (∑_i( a_i,1 - d_i,1 (d_i⋅a_i) ))    (∑_i( a_i,2 - d_i,2 (d_i⋅a_i) ))
          ^
```

**Comment by pressureless** [comment]
I modified the grammar, you need to clean the default parsers in cache directory.

**Comment by yig** [comment]
It compiles now. The Python code doesn't run. I get the following error:

```
Traceback (most recent call last):
  File "Untitled 2.py", line 107, in <module>
    func_value = myExpression(p, d)
  File "Untitled 2.py", line 29, in myExpression
    a[i] = _a_i_0.T - d[i][0] * d[i]
ValueError: could not broadcast input array from shape (3,3) into shape (3,1)
```

The generated code is as follows:

```
import numpy as np
import scipy
import scipy.linalg
from scipy import sparse
from scipy.integrate import quad
from scipy.optimize import minimize


def myExpression(p, d):
    """
    :param :p : ℝ^3: points on lines
    :param :d : ℝ^3: unit directions along lines
    """
    p = np.asarray(p, dtype=np.float64)
    d = np.asarray(d, dtype=np.float64)

    _dim_0 = p.shape[0]
    assert p.shape == (_dim_0, 3)
    assert d.shape == (_dim_0, 3)

    k = np.zeros((_dim_0, 3))
    for i in range(_dim_0):
        k[i] = (p[i] - (np.dot(p[i], d[i])) * d[i])

    _a_i_0 = np.zeros((1, 3))
    _a_i_0[0] = [1, 0, 0]
    a = np.zeros((_dim_0, 3, 1))
    for i in range(_dim_0):
        a[i] = _a_i_0.T - d[i][0] * d[i]

    _b_i_0 = np.zeros((1, 3))
    _b_i_0[0] = [0, 1, 0]
    b = np.zeros((_dim_0, 3, 1))
    for i in range(_dim_0):
        b[i] = _b_i_0.T - d[i][1] * d[i]

    _c_i_0 = np.zeros((1, 3))
    _c_i_0[0] = [0, 0, 1]
    c = np.zeros((_dim_0, 3, 1))
    for i in range(_dim_0):
        c[i] = _c_i_0.T - d[i][2] * d[i]

    _sum_0 = 0
    for i in range(len(d)):
        _sum_0 += (a[i][0] - d[i][0] * (np.dot(d[i], a[i])))
    _sum_1 = 0
    for i in range(len(a)):
        _sum_1 += (a[i][1] - d[i][1] * (np.dot(d[i], a[i])))
    _sum_2 = 0
    for i in range(len(d)):
        _sum_2 += (a[i][2] - d[i][2] * (np.dot(d[i], a[i])))
    _sum_3 = 0
    for i in range(len(d)):
        _sum_3 += (b[i][0] - d[i][0] * (np.dot(d[i], b[i])))
    _sum_4 = 0
    for i in range(len(b)):
        _sum_4 += (b[i][1] - d[i][1] * (np.dot(d[i], b[i])))
    _sum_5 = 0
    for i in range(len(d)):
        _sum_5 += (b[i][2] - d[i][2] * (np.dot(d[i], b[i])))
    _sum_6 = 0
    for i in range(len(d)):
        _sum_6 += (c[i][0] - d[i][0] * (np.dot(d[i], c[i])))
    _sum_7 = 0
    for i in range(len(c)):
        _sum_7 += (c[i][1] - d[i][1] * (np.dot(d[i], c[i])))
    _sum_8 = 0
    for i in range(len(d)):
        _sum_8 += (c[i][2] - d[i][2] * (np.dot(d[i], c[i])))
    _M_0 = np.zeros((3, 3))
    _M_0[0] = [(_sum_0), (_sum_1), (_sum_2)]
    _M_0[1] = [(_sum_3), (_sum_4), (_sum_5)]
    _M_0[2] = [(_sum_6), (_sum_7), (_sum_8)]
    M = _M_0

    _sum_9 = 0
    for i in range(len(a)):
        _sum_9 += (np.dot(k[i], a[i]))
    _sum_10 = 0
    for i in range(len(k)):
        _sum_10 += (np.dot(k[i], b[i]))
    _sum_11 = 0
    for i in range(len(c)):
        _sum_11 += (np.dot(k[i], c[i]))
    _r_0 = np.zeros((3, 1))
    _r_0[0] = [_sum_9]
    _r_0[1] = [_sum_10]
    _r_0[2] = [_sum_11]
    r = _r_0

    q = np.linalg.inv(M) @ r

    return q


def generateRandomData():
    _dim_0 = np.random.randint(10)
    p = np.random.randn(_dim_0, 3)
    d = np.random.randn(_dim_0, 3)
    return p, d


if __name__ == '__main__':
    p, d = generateRandomData()
    print("p:", p)
    print("d:", d)
    func_value = myExpression(p, d)
    print("func_value: ", func_value)
```

**Comment by yig** [comment]
The problem is that this code `[1,0,0]` is generating a column matrix. That makes this `[1,0,0]^T` a row matrix. Adding a vector to a row matrix is adding a column to a row which ends up broadcasting into a 3x3 matrix.

**Comment by pressureless** [comment]
```
_a_i_0 = np.zeros((1, 3))
_a_i_0[0] = [1, 0, 0]```
Why is it a column matrix? The shape of ```_a_i_0``` is still (1, 3)

**Comment by yig** [comment]
Maybe I am diagnosing the problem incorrectly. I still get an error with the latest code in git. Does it work for you? The errors I see now are that:

`np.dot()` is called on two row or column matrices with the same shape, which won't work. `np.dot()` requires the input to be 1D vectors to get the vector dot product. If they are matrices, it performs matrix multiplication.

The right-hand side of `k[i] = (p[i] - (np.dot(p[i], d[i])) * d[i])` is a 2D column matrix, which can't be assigned to the left-hand side which is a 1D vector.

**Comment by pressureless** [comment]
It doesn't work. The shape of ```p[i]```and ```d[i]``` are both ```(3, 1)``` now. Not sure how to fit ```np.dot()```, can we convert them to 1D, it may relate to the vector discussion.

**Comment by yig** [comment]
The way I originally wrote it works now in C++ but not Python (with a change from `<>` to `()` around vectors):

```
given
p_i: ℝ^3: points on lines
d_i: ℝ^3: unit directions along lines

k_i = (p_i - (p_i⋅d_i)d_i)
a_i = (1,0,0) - d_i,1 d_i
b_i = (0,1,0) - d_i,2 d_i
c_i = (0,0,1) - d_i,3 d_i

M = [ ∑_i( a_i,1 - d_i,1 (d_i⋅a_i) )    ∑_i( a_i,2 - d_i,2 (d_i⋅a_i) )    ∑_i( a_i,3 - d_i,3 (d_i⋅a_i) )
      ∑_i( b_i,1 - d_i,1 (d_i⋅b_i) )    ∑_i( b_i,2 - d_i,2 (d_i⋅b_i) )    ∑_i( b_i,3 - d_i,3 (d_i⋅b_i) )
      ∑_i( c_i,1 - d_i,1 (d_i⋅c_i) )    ∑_i( c_i,2 - d_i,2 (d_i⋅c_i) )    ∑_i( c_i,3 - d_i,3 (d_i⋅c_i) ) ]

r = [ ∑_i( k_i⋅a_i )
      ∑_i( k_i⋅b_i )
      ∑_i( k_i⋅c_i ) ]

q = M^(-1) r
```

In Python, I get the error: `Exception: 'SequenceType' object has no attribute 'sparse'`

**Comment by yig** [comment]
The formula for this same problem derived using Frobenius norm manipulation has the same issue. It works in C++ but produces the same error message in Python.

```
given
p_i: ℝ^3: points on lines
d_i: ℝ^3: unit directions along lines

P_i = ( I_3 - d_i d_iᵀ )
q = ( ∑_i P_iᵀP_i )⁻¹ ( ∑_i P_iᵀP_i p_i )
```

The derivation is:

```
Mᵢ = ∑_i (q-p_i) - ((q - p_i) ⋅ d_i) d_i
Eᵢ = Mᵢ:Mᵢ
dEᵢ = 2Mᵢ:dMᵢ
Mᵢ = q - p_i - (q ⋅ d_i) d_i + (p_i ⋅ d_i) d_i
   = q - d_i d_iᵀ q - ( p_i - d_i d_iᵀ p_i )
   = ( I - d_i d_iᵀ ) q - ( I - d_i d_iᵀ ) p_i
P_i = ( I - d_i d_iᵀ )
Mᵢ = P_i q - P_i p_i
dMᵢ = P_i dq
Mᵢ = P_i ( q - p_i )
dEᵢ = 2Mᵢ:dMᵢ = 2Mᵢ:dMᵢ = 2 P_i ( q - p_i ) : P_i dq = 2 P_iᵀP_i ( q - p_i ) : dq
dEᵢ/dq = 2 P_iᵀP_i ( q - p_i )
dE/dq = 2 ∑_i P_iᵀP_i ( q - p_i ) = 0 = ∑_i P_iᵀP_i ( q - p_i ) = ∑_i P_iᵀP_iq - ∑_i P_iᵀP_i p_i
∑_i P_iᵀP_i q = ∑_i P_iᵀP_i p_i
q = ( ∑_i P_iᵀP_i )⁻¹ ( ∑_i P_iᵀP_i p_i )
```

To get I❤️LA from this derivation, I just needed to pull out the last line (defining `q`) and the line in the middle defining `P_i`.
